spring:
  config:
    import: classpath:.env.properties
  datasource:
    url: jdbc:postgresql://localhost:5432/ToDoList
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  application:
    name: ToDoList
  sql:
    init:
      mode: always

server:
  port: 8888

max:
  limit:
    incomplete: 10