spring:
  config:
    import: classpath:.env.properties
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydatabase}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  application:
    name: ToDoList
  sql:
    init:
      mode: always

server:
  port : 8888

max:
  limit:
    incomplete: 10